sentences = ["""She used her own hair in the soup to give it more flavor.""",
"""Everyone was busy, so I went to the movie alone.""",
"""Not all people who wander are lost.""",
"""He dreamed of eating green apples with worms.""",
"""His mind was blown that there was nothing in space except space itself.""",
"""Standing on one's head at job interviews forms a lasting impression.""",
"""The blue parrot drove by the hitchhiking mongoose.""",
"""The shooter says goodbye to his love.""",
"""Greetings from the real universe.""",
"""Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon."""]